# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Recipeapp_development
  host: localhost
  username: postgres
  password: 1234567
  encoding: UTF8
  port: 5432

test:
  <<: *default
  database: Recipeapp_test
  username: postgres
  host: localhost
  password: 1234567

production:
  <<: *default
  database: Recipeapp_production
  username: postgres
  host: localhost
  password: 1234567
